### ISSUE TITLE
[Question] Is the code up-to-date?

### ISSUE THREAD

**Issue by Bluefissure** [goatcorp/XLWebServices#2]
I think the infrastructure of Plogon is not updated, which is used in https://github.com/goatcorp/Plogon/blob/master/Plogon/WebServices.cs#L35 .

Is it used to send Discord webhooks or there's other stuff behind those `Plogon` APIs?

Any plan to update the code so we don't need to reinvent the wheels again?

**Comment by karashiiro** [comment]
This is being updated again, should be safe to close this now

**Comment by Bluefissure** [comment]
> This is being updated again, should be safe to close this now

That's good, btw we have a refactor of xlweb in fastapi but will make it updated as long as this one get updates.

https://github.com/ottercorp/XLWebServices-fastapi
